Possible Bug value typecast in ColumnSchema for JSON DB data type
yiisoft/db-mysql pull request #292
Opened 2023-05-22 18:51 UTC by andryluthfi

PHP Warning — Yiisoft\ErrorHandler\Exception\ErrorException Array to string conversion

i think this occurs when phpTypecast call more than one time. 
- 1st call: Convert string (direct value from DB) to array
- 2nd call: Convert array to array

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |

2023-05-22 18:57 UTC, terabytesoftw commented
Need a unit test, i could add it.

2023-11-09 08:32 UTC, Tigrov requested changes

2023-11-09 08:32 UTC, Tigrov commented on src/ColumnSchema.php
> +            return is_array($value) ? $value : json_decode((string) $value, true, 512, JSON_THROW_ON_ERROR);
```suggestion
            return is_string($value) ? json_decode($value, true, 512, JSON_THROW_ON_ERROR) : $value;
```

Looks better check if it is string

2024-08-19 06:34 UTC, Tigrov commented
Done by https://github.com/yiisoft/db/pull/752

2024-08-19 06:34 UTC, closed without merging