Typecast refactoring
yiisoft/db-mysql pull request #295
Opened 2023-07-04 17:19 UTC by Tigrov

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |

2023-07-06 13:18 UTC, terabytesoftw approved these changes

2023-07-08 18:59 UTC, darkdef requested changes
1. Two type of changes in code: swap methods order and logical refactoring. Need split
2. match(true) - I think this bad practice and not approved this changes. Early exit work fastest.

2023-07-09 04:20 UTC, Tigrov commented
> 1. Two type of changes in code: swap methods order and logical refactoring. Need split
> 2. match(true) - I think this bad practice and not approved this changes. Early exit work fastest.

1. Ok, agree. Thanks.
2. Why do you think `this bad practice`?
> Early exit work fastest.

In the case `=> $value` equals `return $value`

For me `match (true)` looks better than a lot of `if`
https://github.com/yiisoft/yii-queue/blob/master/src/Debug/QueueCollector.php#L37
https://github.com/yiisoft/log/blob/master/src/Message/Formatter.php#L148
https://github.com/yiisoft/yii-widgets/blob/master/src/Dropdown.php#L639

2023-07-09 09:36 UTC, darkdef commented
> 2\. Why do you think `this bad practice`?

Match with short and simple condition - good solution (as examples from other packages), but in this case we have complex conditions.

2023-07-13 17:58 UTC, darkdef commented on tests/Support/Fixture/mysql.sql
> +  `bit_col_1` BIT(1) NOT NULL DEFAULT b'0',
I think - it's reduce integration test coverage.

2023-07-13 17:58 UTC, darkdef commented on tests/Provider/SchemaProvider.php
> +                        'defaultValue' => false,
it's reduce integration test coverage?

2023-07-15 05:01 UTC, Tigrov commented on tests/Provider/SchemaProvider.php
> +                        'defaultValue' => false,
I think this line reduse it
https://github.com/yiisoft/db-mysql/pull/295/files#diff-aba1adae571d18ad5f7c6db19cfd8f15eb41daae1806924278c9a119f7c8b6daR564

Tests added

2023-07-15 07:24 UTC, darkdef commented on src/Schema.php
> +            $type = $matches[1];
Please return strtolower.
User can use constant PDO::CASE_UPPER in connection

2023-07-16 14:26 UTC, darkdef approved these changes

2023-07-16 14:27 UTC, merged

2023-07-16 14:27 UTC, darkdef commented
Great work. Thanks