Refactor `Quoter::quoteValue()` method
yiisoft/db-mysql pull request #366
Opened 2024-11-20 03:17 UTC by Tigrov

### Related PR
- https://github.com/yiisoft/db/pull/902

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  |

2024-11-20 11:25 UTC, samdark requested changes

2024-11-20 11:25 UTC, samdark commented on src/Column.php
> +        return ' COMMENT ' . (new Quoter('`', '`'))->quoteValue($this->getComment() ?? '');
Should we return empty instead of `COMMENT ` in this case? I think comment w/o value will give you error, won't it?

2024-11-21 09:36 UTC, Tigrov commented on src/Column.php
> +        return ' COMMENT ' . (new Quoter('`', '`'))->quoteValue($this->getComment() ?? '');
It returns empty if comment is `null`. Empty string means that comment is empty string. It is possible in some DBMS.

2024-11-22 19:38 UTC, samdark commented on src/Column.php
> +        return ' COMMENT ' . (new Quoter('`', '`'))->quoteValue($this->getComment() ?? '');
OK.

2024-11-22 19:38 UTC, samdark approved these changes

2024-11-23 01:35 UTC, merged